donatespectacles/urls.py
from django.conf.urls import patterns, include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'donatespectacles.views.home', name='home'),
    # url(r'^donatespectacles/', include('donatespectacles.foo.urls')),
    url(r'^home/', include('workflow.urls')),
    url(r'^$', include('workflow.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

workflow/urls.py
from django.conf.urls import patterns, url

from workflow import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^how$', views.how, name='how'),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^ngo$', views.ngo, name='ngo'),
    url(r'^optical$', views.optical, name='optical'),
    url(r'^corporate$', views.corporate, name='corporate'),
    url(r'^search$', views.search, name='search')
)

workflow/models.py
from django.db import models

class Power(models.Model):
    	right_distance_spherical = models.FloatField(default=0)
    	right_distance_cylinderical = models.FloatField(default=0)
	right_distance_cylinderical_axis = models.FloatField(default=0)
	right_near_spherical = models.FloatField(default=0)
        right_near_cylinderical = models.FloatField(default=0)
        right_near_cylinderical_axis = models.FloatField(default=0)
	right_prism = models.FloatField(default=0)
	left_distance_cylinderical_axis = models.FloatField(default=0)
	left_distance_cylinderical = models.FloatField(default=0)
	left_distance_spherical = models.FloatField(default=0)
        left_near_spherical = models.FloatField(default=0)
        left_near_cylinderical = models.FloatField(default=0)
        left_near_cylinderical_axis = models.FloatField(default=0)
	left_prism = models.FloatField(default=0)
	add = models.FloatField(default=0)
	def __unicode__(self):
		right_eye =  u'OD -%s +%s SPH -%s x%s +%s x%s %s add %s p.d' % (self.right_distance_spherical,self.right_near_spherical,self.right_distance_cylinderical,self.right_distance_cylinderical_axis, self.right_near_cylinderical, self.right_near_cylinderical_axis,self.add,self.right_prism)
		left_eye =  u'OD -%s +%s SPH -%s x%s +%s x%s %s add %s p.d' % (self.left_distance_spherical,self.left_near_spherical,self.left_distance_cylinderical,self.left_distance_cylinderical_axis, self.left_near_cylinderical, self.left_near_cylinderical_axis,self.add,self.left_prism)
	        return right_eye+'::'+left_eye

class Optician(models.Model):
	name = models.CharField(max_length=400)
	address = models.CharField(max_length=600)
	emailId = models.EmailField(max_length=200)
	image_logo = models.SlugField(max_length=600)
	phone = models.BigIntegerField(default=0)

class NGO(models.Model):
	name = models.CharField(max_length=400)
        address = models.CharField(max_length=600)
        emailId = models.EmailField(max_length=200)
        image_logo = models.SlugField(max_length=600)
        phone = models.BigIntegerField(default=0)

class Location(models.Model):
	name = models.CharField(max_length=400)
        address = models.CharField(max_length=600)
        emailId = models.EmailField(max_length=200)
        image_logo = models.SlugField(max_length=600)
        phone = models.BigIntegerField(default=0) 
	def __unicode__(self):
		return self.name

	

class Spectacle(models.Model):
	SIZES = (
        	('S', 'Kids'),
	        ('M', 'Medium'),
        	('L', 'Large'),
   	 )
    	id = models.AutoField(primary_key=True)
	email_id = models.EmailField(max_length=200)
	size = models.CharField(max_length=1,choices=SIZES)
	donate_date = models.DateField(auto_now_add=True)
	location = models.ForeignKey(Location,null=False)
	power = models.ForeignKey(Power,null=True)
	date_recieved = models.DateTimeField('date recived', blank=True, null=True)
	processed_by = models.ForeignKey(Optician,null=True)
	donated_to = models.ForeignKey(NGO,null=True)
	final_comments = models.CharField(max_length=400,null=True)
	donation_image = models.SlugField(max_length=400,null=True) 

workflow/forms.py
from django.forms import ModelForm
from workflow.models import Spectacle

class DonateForm(ModelForm):	
	class Meta:
		model = Spectacle
	        fields = ['email_id', 'size','location']

workflow/views.py
# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render
from workflow.forms import DonateForm
from workflow.models import Spectacle
from django.core.mail import send_mail


def get_total_donation():
	return Spectacle.objects.count()

def mail(to,subject,content):
	send_mail(subject, content, "donateoldspectacles@gmail.com", [to], fail_silently=False)

def index(request):
	if request.method == 'POST':
        	form =DonateForm(request.POST)
        	if form.is_valid():
            		donate = form.save()
			id = donate.id
			location = donate.location
			message="""
Hello,

Thanks for your donation.
Your donation id is %s. Please wrap the spectacles with a piece of paper with this id written and drop it at %s.
Please visit http://www.donateoldspectacles.org/home/search?query=%s to track your donation.
				
Regards,
DonateoldSpectacles.org Team.
					
			""" % (("BS00"+str(id)),("BS00"+str(id)),location)
			mail(donate.email_id,"Thanks for your donation",message)

			context =  { 'latest_count': get_total_donation(),
                     		     'form' : form,
				     'donate_id': id,
				     'donate_location' : location,
                	}
		else: #Form error scenario
			context =  { 'latest_count': get_total_donation(),
                     		     'form' : form,
                	}

	else:
		form = DonateForm()
		context =  { 'latest_count': get_total_donation(),
		     'form' : form,
		}
	return render(request, 'index.html', context)

def how(request):
	context =  { 'latest_count': get_total_donation(),}
	return render(request, 'how.html', context)

def contact(request):
	context = { 'latest_count':get_total_donation() }
	return render(request,'contact.html',context)

def ngo(request):
	context = { 'latest_count':get_total_donation() }
	return render(request,'ngo.html',context)

def optical(request):
	context = { 'latest_count':get_total_donation() }
	return render(request,'optical.html',context)

def corporate(request):
	context = { 'latest_count':get_total_donation() }
	return render(request,'corporate.html',context)

def search(request):
	query=request.GET['query']
	query_id=query.replace("BS00","")
	data = Spectacle.objects.filter(id__iexact=query_id) | Spectacle.objects.filter(email_id__icontains=query)
	context = { 'latest_count':get_total_donation(),
		    'data':data		
	 }
	return render(request,'search.html',context)

donatespectacles/templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Donate Old Spectacles</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href={% static "/static/css/bootstrap.css" %} rel="stylesheet">
    <style>
	* {
	margin: 0;
	}
	html, body {
		height: 100%;
	}
	/* Wrapper for page content to push down footer */
      #wrap {
        min-height: 100%;
        height: auto !important;
        height: 100%;
        /* Negative indent footer by it's height */
        margin: 0 auto -85px;
      }

      /* Set the fixed height of the footer here */
      #push,
      #footer {
        height: 85px;
	clear:both;
      }
      #footer {
        background-color: #3B5998;
      }

      /* Lastly, apply responsive CSS fixes as necessary */
      @media (max-width: 767px) {
        #footer {
          margin-left: -20px;
          margin-right: -20px;
          padding-left: 20px;
          padding-right: 20px;
        }
      }



      /* Custom page CSS
      -------------------------------------------------- */
      /* Not required for template or sticky footer method. */

     .credit {
        margin: 5px 5px;
      } 
    </style>
    <link href="{%static "/static/css/bootstrap-responsive.css" %}" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="http://twitter.github.io/bootstrap/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="http://twitter.github.io/bootstrap/assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="http://twitter.github.io/bootstrap/assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="http://twitter.github.io/bootstrap/assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="http://twitter.github.io/bootstrap/assets/ico/favicon.png">

    <!-- Google Analytics Code -->
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	ga('create', 'UA-46625840-1', 'donateoldspectacles.org');
      	ga('send', 'pageview');
   </script>
    <script type="text/javascript">

    (function(i,s,o,g,r,a,m){i['BakBakObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;a.id='bakbakscript';m.parentNode.insertBefore(a,m)
      })(window,document,'script','http://bakbakio.herokuapp.com/js/bakbak.js?id=532979a2950c530200afb71b','bakbak');
        </script>
  </head>

  <body>
	<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=188268405971";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


      <!-- Fixed navbar -->
      <div id="wrap">
      <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="brand" href="/home"><img src ="{% static 'images/logo.svg' %}" width="25px" height="40px"/></a>
            <div class="nav-collapse collapse">
              <ul class="nav">
		<li><a href="/home/how">How</a></li>
                <li><a href="/home/contact">Who</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Partner<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="/home/ngo">NGO</a></li>
                    <li><a href="/home/optical">Opticals</a></li>
                    <li><a href="/home/corporate">Corporate</a></li>
                    <li class="divider"></li>
                    <li class="nav-header">Others</li>
                    <li><a href="#">Volunteer</a></li>
                    <li><a href="#">Media</a></li>
                  </ul>
		<li><a>Total Donations: {{ latest_count}}</a></li>
	  	</li>
            </li> 
	    </li> 
	    </ul>
            </div><!--/.nav-collapse -->
	<div class="credit navbar-form pull-left">
	<form class="form-search" method="GET" action="/home/search" style="margin:0px" >
  	<div class="input-append" style="margin:0px">
	<input type="text" class="input-large search-query" name="query" placeholder="Search Email or id" />
  	<button type="submit" class="btn"><i class="icon-search icon-white"></i></button>
	</div>
	</form>
	</div>
	<div class="credit navbar-form pull-right">
         <div class="fb-like" data-href="https://www.facebook.com/donateoldspectacles" data-width="50" data-action="like" data-show-faces="false" data-send="false" data-layout="button_count"></div>
          </div>

	</div>
        </div>
</div>

      <!-- Begin page content -->
      <div class="container">
        {% block content %}{% endblock %}
      </div>
	</div>
	<div id='push'></div>
	</div>
	<div id="footer">
      		<div class="container">
        		<div class="muted credit">
		Website developed and maintained by <a href="http://www.facebook.com/biplav.saraf" target="_blank">Biplav Saraf</a><div class="fb-follow" data-href="https://www.facebook.com/biplav.saraf" data-width="450" data-colorscheme="dark" data-layout="box_count" data-show-faces="false"></div>
			</div>
		 </div>
      </div>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src={% static "/static/jquery.js" %}></script>
    <script src={% static "/static/bootstrap-transition.js"%}></script>
    <script src={% static "/static/bootstrap-alert.js"%}></script>
    <script src={% static "/static/bootstrap-modal.js"%}></script>
    <script src={% static "/static/bootstrap-dropdown.js"%}></script>
    <script src={% static "/static/bootstrap-scrollspy.js"%}></script>
    <script src={% static "/static/bootstrap-tab.js"%}></script>
    <script src={% static "/static/bootstrap-tooltip.js"%}></script>
    <script src={% static "/static/bootstrap-popover.js"%}></script>
    <script src={% static "/static/bootstrap-button.js"%}></script>
    <script src={% static "/static/bootstrap-collapse.js"%}></script>
    <script src={% static "/static/bootstrap-carousel.js"%}></script>
    <script src={% static "/static/bootstrap-typeahead.js"%}></script>

  

</body></html>

donatespectacles/templates/contact.html
{% extends "base.html" %}

{% block content %}
<div style="padding-top:60px">
<div id = "about_us">
<div class ="page-header">
<p class="lead"><h1>Who are we?</h1> </p>
</div>
  Our organization, we aim at creating a self sustainable model for recycling old spectacles and making it
reach the needy. This model is not possible without the donor, the receiver, and an optician. Hence, we are trying to
reach out to as many people who fall in the three categories to make this non-profit motive project a success.
 For the benefit of our valuable donors, opticians, NGO’s (who will help us reach the end users), we will provide a 
common IT platform which can be accessible by all our stakeholders to check the requirement list, current status of
the spectacle inventory available with us and also provide the donor an option to track the status of his/her donated 
spectacle.
To kick start with the collection of old spectacles, we are looking at corporate offices and similar institutions to get the 
required numbers whose power will be monitored by our opticians and promptly be updated on the website, ready to 
be picked by the NGO’s. 
Apart from a great sense of satisfaction, we shall express our gratitude to the donor by offering a discount voucher 
from one amongst the leading eyewear retail outlets on their next purchase of the spectacle from the store.
So, lets join our hands together to make the other person’s life brighter as easily by making the little effort of donating 
your old spectacles that are lying unattended at the shelf!
</div>
 
<div class="page-header">
  <h1>Contact</h1>
</div>
<!-- Example row of columns -->
      <div class="row">
        <div class="span4">
	<p><h4>Mail</h4></p>
	<address>
  	<strong>DonateoldSpectacles.org</strong><br>
  	<a href="mailto:#">donateoldspectacles@gmail.com</a><br>
  	<abbr title="Phone">P:</abbr> (+91) 9844186612<br>
	</address>
        </div>
        <div class="span4">
	<p><h4>Shout</h4></p>
	<div class="fb-comments" data-href="https://www.facebook.com/donateoldspectacles" data-width="470"></div>
	</div>
      </div>
  </div>
</div>
{% endblock %}

donatespectacles/templates/corporate.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="main" style="padding-top:60px">
<div class="page-header">
<h4>Institutions currently partnered with us.</h4>
</div>
<div id="myCarousel" class="carousel slide" style="width: 770px; margin: 0 auto">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item">
         <img src={% static "images/carousel-image.png" %} alt="">
          <div class="carousel-caption">
	          <h4>Your Brand</h4>
                      <p>See your brand here and help the cause.</p>
           </div>
    </div>
    <div class="item">
	<img src={% static "images/carousel-image.png" %} alt="">
          <div class="carousel-caption">
                  <h4>Your Brand</h4>
                      <p>See your brand here and help the cause.</p>
           </div>
   </div>
    <div class="item">
	<img src={% static "images/carousel-image.png" %} alt="">
          <div class="carousel-caption">
                  <h4>Your Brand</h4>
                      <p>See your brand here and help the cause</p>
           </div>
    </div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
<div id="content-data">
<br>
Institutions and Corporates run our donateoldspectacles campaign by putting a dropbox at their location and popularising the same across their employees/members/facutly/visitors. We provide a kit to do that, which includes email, posters and dropbox. And the people making donations are also benefited with the vouchers and discount coupons provided by our optical partners.<br>
To run such a campaign in your organisation or institution please get in touch with us.
<br><br>
<address>
  <strong>DonateoldSpectacles.org</strong><br>
  <a href="mailto:#">donateoldspectacles@gmail.com</a><br>
  <abbr title="Phone">P:</abbr> (+91) 9844186612<br>
</address>
</div>
</div>
{% endblock %}

donatespectacles/templates/how.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div style="padding-top:60px">
	<div class="page-header">
  		<h1>How it works?</h1>
	</div>
	<div class="row">
        	<div class="span5">
          		<h4>Fill the form on the website.</h4>
          		<p><div class="media">
                    		<img class="img-rounded" src="{% static "images/how-1.png" %}" />
        		</div></p>
		</div>
	<div class="span5">
                        <h4>Note the id and share it on facebook.</h4>
                        <p><div class="media">
                                <img class="img-rounded" src="{% static "images/how-2.png" %}" />
                        </div></p>
                </div>
	</div>
	<div class="row">
        	<div class="span5">
          		<h4>Wrap the spectacle with a paper with the id on it and drop it in donation box.</h4>
          		<p><div class="media">
                    		<img class="img-rounded" src="{% static "images/how-3.png" %}" />
        		</div></p>
		</div>
	<div class="span5">
                        <h4>Use search box to track the status of your donation</h4>
                        <p><div class="media">
                                <img class="img-rounded" src="{% static "images/how-4.png" %}" />
                        </div></p>
                </div>
	</div>


</div>
{% endblock %}

donatespectacles/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="hero-unit">
  <h1>Donate old spectacle</h1>
  {%if donate_id %}
	<p class="lead"> Thanks for your donation! </p>
  	<p>Please write the number BS00{{ donate_id }} on the paper used to wrap the specatacle with before putting it in the donation box at {{ donate_location}}. </p>
	<a href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fwww.donateoldspectacles.org%2Fhome%2Fsearch%3Fquery%3DBS00{{ donate_id }}" target="_blank">
<img src={% static "images/facebook-share.gif" %} alt="Share on Facebook" />
</a>
  {% else %} 
  <p>Fill in the below form before dropping the spectacle in the drop box.</p> 
	<div id="push lead">
		{% if form.email_id.error or form.size.errors%}
		<span class="label label-important">
			{% if form.email_id.errors%}
            		Email: {% for e in form.email_id.errors %} {{e}} {% endfor %}
			{% endif %}
			{% if form.size.errors%}
                         Size: {% for e in form.size.errors %} {{e}} {% endfor %}
                        {% endif %}
			{% if form.location.errors%}
                         Location: {% for e in form.location.errors %} {{e}} {% endfor %}
                        {% endif %}
		</span>
		{% endif %}
		<form action="." method="post" class="form-inline">{% csrf_token %}
		{% if form.email_id.errors %}
			<div class="control-group error help-inline" >
		{% endif %}
		<input id="id_email_id" maxlength="200" name="email_id" type="text" placeholder="Email">
		{% if form.email_id.errors  %}
			</div>
		{% endif %}
		{% if form.size.errors %}
			<div class="control-group error help-inline" >
		{% endif %}
		{{ form.size }}
		{% if form.size.errors  %}
			</div>
		{% endif %}
		{% if form.location.errors %}
                        <div class="control-group error help-inline" >
                {% endif %}
                {{ form.location }}
                {% if form.location.errors  %}
                        </div>
		{% endif %}
		<input type="submit" value="Donate" class="btn btn-primary"/>
		</form>
	<p>Your donation goes to the people who need your old spectacle and you can track it using the searchbox above.</p>
	</div>
  {% endif %}
</div>
<!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>NGO Partners</h2>
          <p><div class="media">
		<a target="_blank" href="http://snehadeep.org.in/" class="pull-left">
			<img class="media-object" src="{% static "images/snehadeep.png" %}" />
		</a>
		<div class="media-body">
    		<h4 class="media-heading">Snehadeep Trust for Disabled</h4>
		Snehadeep Trust for the Disabled was established in 1999 by three visually impaired graduates, who had a strong will to empower the disabled with life opportunities, which they had fought so hard for.
		</div>
	</div>
	<h6> We are looking for more partners. </h6>
	</p>
          <p><a class="btn" href="/home/ngo">Join us&raquo;</a></p>
        </div>
        <div class="span4">
          <h2>Optical Partners</h2>
	<div class="media">
                <a target="_blank" href="http://www.donateoldspectacles.org/" class="pull-left">
                        <img class="media-object" src="{% static "images/blank.png" %}" />
                </a>
                <div class="media-body">
                <h4 class="media-heading">Be Featured here.</h4>
		Currently we are looking for opticals to support us in this noble cause. If you are interested in helping us, please write to us. This is a symbiotic relationship as we help the opticals in generating more leads and aquiring more cutomers.
                </div>
        </div></p>
        <a class="btn" href="/home/optical">Support us &raquo;</a></p>
       </div>
        <div class="span4">
          <h2>Institutional Partners</h2>
	<div class="media">
                <a target="_blank" href="http://www.donateoldspectacles.org/" class="pull-left">
                        <img class="media-object" src="{% static "images/blank.png" %}" />
                </a>
                <div class="media-body">
                <h4 class="media-heading">Be Featured here.</h4>
               As a corporate organisation, you can run campaingns to collect old spectacles from the employees and hand it over to us. Running such campaign is simple and hassle free. We provide instructions and kit to run this campaign. Your employees can also benefits from the same as we provide them with discount coupons for next purchase. And the entire process is transparent as one can track the donation on the site with their email ids.
                </div>
        </div></p>

          <a class="btn" href="/home/corporate">View details &raquo;</a></p>
        </div>
      </div>

{% endblock %}

donatespectacles/templates/ngo.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="main" style="padding-top:60px">
<div class="page-header">
<h4>NGO's we are currently working with</h4>
</div>
<div id="myCarousel" class="carousel slide" style="width: 770px; margin: 0 auto">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item">
         <img src={% static "images/snehadeep_main.png" %} alt="">
          <div class="carousel-caption">
	          <h4>Snehadeep Trust for Disabled</h4>
                      <p>Snehadeep Trust for the Disabled was established in 1999 by three visually impaired graduates, who had a strong will to empower the disabled with life opportunities, which they had fought so hard for.</p>
           </div>
    </div>
    <div class="item">
	<img src={% static "images/carousel-image.png" %} alt="" style="align:center">
          <div class="carousel-caption">
                  <h4>Your NGO</h4>
                      <p>Contact us and get a list of all our donation to suffice your requirement.</p>
           </div> 
   </div>
    <div class="item">
	<img src={% static "images/snehadeep_main.png" %} alt="">
          <div class="carousel-caption">
                  <h4>Snehadeep Trust for Disabled</h4>
                      <p>Snehadeep Trust for the Disabled was established in 1999 by three visually impaired graduates, who had a strong will to empower the disabled with life opportunities, which they had fought so hard for.</p>
           </div>
    </div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
<div id="content-data">
We provide these ngo's with a list of available spectacles and deliver to them based on their requirements. We are looking to add more such NGO's to the list so that we can be more effective. If you are an NGO and would have need for spectacles, then please get in touch with us and we would make an arrangement to add you on our list of Partner NGO's.
<br><br>
<address>
  <strong>DonateoldSpectacles.org</strong><br>
  <a href="mailto:#">donateoldspectacles@gmail.com</a><br>
  <abbr title="Phone">P:</abbr> (+91) 9844186612<br>
</address>
</div>
</div>
{% endblock %}

donatespectacles/templates/optical.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="main" style="padding-top:60px">
<div class="page-header">
<h4>Opticals currently partnered with us.</h4>
</div>
<div id="myCarousel" class="carousel slide" style="width: 770px; margin: 0 auto">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item">
         <img src={% static "images/carousel-image.png" %} alt="">
          <div class="carousel-caption">
	          <h4>Your Brand</h4>
                      <p>See your brand here and get featured to reach all our donors.</p>
           </div>
    </div>
    <div class="item">
	<img src={% static "images/carousel-image.png" %} alt="">
          <div class="carousel-caption">
                  <h4>Your Brand</h4>
                      <p>See your brand here and get featured to reach all our donors.</p>
           </div>
   </div>
    <div class="item">
	<img src={% static "images/carousel-image.png" %} alt="">
          <div class="carousel-caption">
                  <h4>Your Brand</h4>
                      <p>See your brand here and get featured to reach all our donors.</p>
           </div>
    </div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
<div id="content-data">
<br>
The opticals partnered with us have huge benefits, as we help them reach their target audience and lead generations at literally no cost. In return, we expect them to help us measure the power reading of the glasses donated and update it in our database, so the right glasses can be provided to the one who needs it.
We work with institutions, corporates and NGO's. All optical partner can see their brands displayed on all out posters and on social media. If you are interested in helping us, then please get in touch.
<br><br>
<address>
  <strong>DonateoldSpectacles.org</strong><br>
  <a href="mailto:#">donateoldspectacles@gmail.com</a><br>
  <abbr title="Phone">P:</abbr> (+91) 9844186612<br>
</address>
</div>
</div>
{% endblock %}

donatespectacles/templates/search.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% load static %}

{% block content %}
        <link rel="stylesheet" href="{% static "css/screen.css" %} " />
<div style="padding-top:60px">
<div class="page-header">
  <h1>Search Result</h1>
</div>
<div id="results">
	{% if data %}
	{% render_table data %}
	{% else %}
	<h4> No donation found of the given email or id.</h4>
	{% endif %}
</div>
{% endblock %}